### PR TITLE
Feature: Variant annotations

### PR DESCRIPTION
**Pull request by pcingola**
Hi everyone,
  This is a pull request for adding an Avro IDL file for variant annotations (annotations.avdl). 
  Annotations include records for variant effect, impact, coding and non-coding information, 
clinical relevance, etc.
  It is heavily based on VEP (ENSEMBL's Variant Effect Predictor) and SnpEff (an annotations 
tool I wrote).

### CODE REVIEW

**Comment by kellrott** [comment]
What's going on with this PR? There hasn't been any movement in 4 months.

**Comment by sarahhunt** [comment]
Hi Kyle,

There have been discussions ongoing in the Variation Annotation group 
and we'll be putting forward an new schema next week. We decided it was 
simpler to start afresh than modify the original PR as much has changed 
in the intervening time.

**Comment by kellrott** [comment]
Good to hear the work is going on. It would be nice of the variant annotations reconciled their concept of genes with the sequence annotation structures that are currently being proposed in https://github.com/ga4gh/schemas/pull/246

**Comment by sarahhunt** [comment]
That's the plan!

**Comment by jacmarjorie** [comment]
I know this is a work in progress, but looking over the code last week there is reference to a GAEffect, which I am assuming would align to the MAF mutation Variant_Classification (frameshift, missense etc.) was referenced but not defined anywhere.

**Comment by sarahhunt** [comment]
Hi Jaclyn,

We've put together a new basic schema in a variation_annotation branch 
as the original PR was out of date. You can see the proposed changes here:

https://github.com/ga4gh/schemas/blob/variation_annotation/src/main/resources/avro/variants.avdl
https://github.com/ga4gh/schemas/blob/variation_annotation/src/main/resources/avro/variantmethods.avdl

It only attempts to cover the minimal set of attributes the group agreed 
on in an earlier call but should be a starting point for further 
discussions and iterations

Sarah

**Comment by david4096** [comment]
Closing given https://github.com/ga4gh/schemas/pull/519

**Pull request closed without merging**
