### PR TITLE
geodata object and implementations

### PR DESCRIPTION
**Pull request by mbaudis**
This is a go at the previously discussed geodata object. See e.g.
* Geodata object issue https://github.com/ga4gh/ga4gh-schemas/issues/771
* Google doc with current notes https://docs.google.com/document/d/1PBIlNtxJAXe2K1wwTlPMNO4N0e03uejl8Da14RtEjJg/edit#
* "old" metadata dev notes https://github.com/ga4gh/ga4gh-schemas/blob/metadata/src/main/resources/avro/metadata.avdl#L47

### CODE REVIEW

**Comment by helenp** [comment]
Summarising here from the notes document: 
"As a pragmatic approach, the combination of lat,long + a (geonames.org mapped) location name seems the best compromise, with the addition of a “precision level” providing additional features (e.g. possibility to randomize point locations in a given boundary)."

**Comment by helenp** [comment]
+1

**Comment by mbaudis** [comment]
@ejacox Thanks - great! Now, (also @kozbo, @david4096), how/when can we get this as a pick -> push_to_master? IMHO any time ...

**Comment by ejacox** [comment]
I didn't realize you were working on a branch of master. I thought we were only forking from master (is that right @kozbo, @david4096?). Anyways, I will let @kozbo merge the branch since that will signify that we are no longer keeping the reference server in sync with the schemas.

**Comment by mbaudis** [comment]
The `metadata-integration` is thought as a staging branch for master. We had discussed this in Vancouver as a practical way to collect major "metadata" code updates, which however all are intended to be merged to master at some point. It is up to the schema integration team to select what & when is merged ... 

So for me, changes in the `metadata-integration` are "forward looking" and can be used as basis for to add features to our test implementations.

**Comment by ejacox** [comment]
Thank you for the clarification @mbauds.

**Pull request merged**
